### ISSUE TITLE
Update to the latest version (current 3.3.3)

### ISSUE THREAD

**Issue by marcuslma** [BigDSK/meteor-inputmask#4]
Can you update to the latest version?
The current version is 3.3.3
Thank you in advance!

**Comment by BigDSK** [comment]
Hi @marcuslma -- Updated and published. If you're on Meteor 1.3+ I'd recommend a move to a direct dependency via NPM. https://www.npmjs.com/package/jquery.inputmask

**Comment by marcuslma** [comment]
Thank you very much. :)
Yes, I am using 1.3+.
I'll follow your recomendation.
Best regards.
